[package]
name = "quick-protobuf"
description = "A pure Rust protobuf (de)serializer. Quick."
version = "0.8.0"
authors = ["Johann Tuffe <tafia973@gmail.com>"]
keywords = ["protobuf", "parser"]
license = "MIT"
readme = "README.md" 
documentation = "https://docs.rs/quick-protobuf"
repository = "https://github.com/tafia/quick-protobuf"
edition = "2018"

[dependencies]
byteorder = { version = "1.3.4", default-features = false }
heapless = "0.7.8"

[dev-dependencies]
lazy_static = "1.4.0"

[features]
default = ["std"]
std = ["byteorder/std", "alloc"]
alloc = []
