// This file is generated by rust-protobuf 2.25.2. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `perftest_data.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_25_2;

#[derive(PartialEq,Clone,Default)]
pub struct Test1 {
    // message fields
    value: ::std::option::Option<i32>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Test1 {
    fn default() -> &'a Test1 {
        <Test1 as ::protobuf::Message>::default_instance()
    }
}

impl Test1 {
    pub fn new() -> Test1 {
        ::std::default::Default::default()
    }

    // optional int32 value = 1;


    pub fn get_value(&self) -> i32 {
        self.value.unwrap_or(0)
    }
    pub fn clear_value(&mut self) {
        self.value = ::std::option::Option::None;
    }

    pub fn has_value(&self) -> bool {
        self.value.is_some()
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: i32) {
        self.value = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for Test1 {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.value = ::std::option::Option::Some(tmp);
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(v) = self.value {
            my_size += ::protobuf::rt::value_size(1, v, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(v) = self.value {
            os.write_int32(1, v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Test1 {
        Test1::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "value",
                |m: &Test1| { &m.value },
                |m: &mut Test1| { &mut m.value },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Test1>(
                "Test1",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Test1 {
        static instance: ::protobuf::rt::LazyV2<Test1> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Test1::new)
    }
}

impl ::protobuf::Clear for Test1 {
    fn clear(&mut self) {
        self.value = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Test1 {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Test1 {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct TestRepeatedBool {
    // message fields
    pub values: ::std::vec::Vec<bool>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TestRepeatedBool {
    fn default() -> &'a TestRepeatedBool {
        <TestRepeatedBool as ::protobuf::Message>::default_instance()
    }
}

impl TestRepeatedBool {
    pub fn new() -> TestRepeatedBool {
        ::std::default::Default::default()
    }

    // repeated bool values = 1;


    pub fn get_values(&self) -> &[bool] {
        &self.values
    }
    pub fn clear_values(&mut self) {
        self.values.clear();
    }

    // Param is passed by value, moved
    pub fn set_values(&mut self, v: ::std::vec::Vec<bool>) {
        self.values = v;
    }

    // Mutable pointer to the field.
    pub fn mut_values(&mut self) -> &mut ::std::vec::Vec<bool> {
        &mut self.values
    }

    // Take field
    pub fn take_values(&mut self) -> ::std::vec::Vec<bool> {
        ::std::mem::replace(&mut self.values, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for TestRepeatedBool {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_bool_into(wire_type, is, &mut self.values)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += 2 * self.values.len() as u32;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.values {
            os.write_bool(1, *v)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TestRepeatedBool {
        TestRepeatedBool::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_vec_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                "values",
                |m: &TestRepeatedBool| { &m.values },
                |m: &mut TestRepeatedBool| { &mut m.values },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TestRepeatedBool>(
                "TestRepeatedBool",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TestRepeatedBool {
        static instance: ::protobuf::rt::LazyV2<TestRepeatedBool> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TestRepeatedBool::new)
    }
}

impl ::protobuf::Clear for TestRepeatedBool {
    fn clear(&mut self) {
        self.values.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TestRepeatedBool {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TestRepeatedBool {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct TestRepeatedPackedInt32 {
    // message fields
    pub values: ::std::vec::Vec<i32>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TestRepeatedPackedInt32 {
    fn default() -> &'a TestRepeatedPackedInt32 {
        <TestRepeatedPackedInt32 as ::protobuf::Message>::default_instance()
    }
}

impl TestRepeatedPackedInt32 {
    pub fn new() -> TestRepeatedPackedInt32 {
        ::std::default::Default::default()
    }

    // repeated int32 values = 1;


    pub fn get_values(&self) -> &[i32] {
        &self.values
    }
    pub fn clear_values(&mut self) {
        self.values.clear();
    }

    // Param is passed by value, moved
    pub fn set_values(&mut self, v: ::std::vec::Vec<i32>) {
        self.values = v;
    }

    // Mutable pointer to the field.
    pub fn mut_values(&mut self) -> &mut ::std::vec::Vec<i32> {
        &mut self.values
    }

    // Take field
    pub fn take_values(&mut self) -> ::std::vec::Vec<i32> {
        ::std::mem::replace(&mut self.values, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for TestRepeatedPackedInt32 {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_int32_into(wire_type, is, &mut self.values)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.values.is_empty() {
            my_size += ::protobuf::rt::vec_packed_varint_size(1, &self.values);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.values.is_empty() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            // TODO: Data size is computed again, it should be cached
            os.write_raw_varint32(::protobuf::rt::vec_packed_varint_data_size(&self.values))?;
            for v in &self.values {
                os.write_int32_no_tag(*v)?;
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TestRepeatedPackedInt32 {
        TestRepeatedPackedInt32::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_vec_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "values",
                |m: &TestRepeatedPackedInt32| { &m.values },
                |m: &mut TestRepeatedPackedInt32| { &mut m.values },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TestRepeatedPackedInt32>(
                "TestRepeatedPackedInt32",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TestRepeatedPackedInt32 {
        static instance: ::protobuf::rt::LazyV2<TestRepeatedPackedInt32> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TestRepeatedPackedInt32::new)
    }
}

impl ::protobuf::Clear for TestRepeatedPackedInt32 {
    fn clear(&mut self) {
        self.values.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TestRepeatedPackedInt32 {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TestRepeatedPackedInt32 {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct TestRepeatedMessages {
    // message fields
    pub messages1: ::protobuf::RepeatedField<TestRepeatedMessages>,
    pub messages2: ::protobuf::RepeatedField<TestRepeatedMessages>,
    pub messages3: ::protobuf::RepeatedField<TestRepeatedMessages>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TestRepeatedMessages {
    fn default() -> &'a TestRepeatedMessages {
        <TestRepeatedMessages as ::protobuf::Message>::default_instance()
    }
}

impl TestRepeatedMessages {
    pub fn new() -> TestRepeatedMessages {
        ::std::default::Default::default()
    }

    // repeated .perftest_data.TestRepeatedMessages messages1 = 1;


    pub fn get_messages1(&self) -> &[TestRepeatedMessages] {
        &self.messages1
    }
    pub fn clear_messages1(&mut self) {
        self.messages1.clear();
    }

    // Param is passed by value, moved
    pub fn set_messages1(&mut self, v: ::protobuf::RepeatedField<TestRepeatedMessages>) {
        self.messages1 = v;
    }

    // Mutable pointer to the field.
    pub fn mut_messages1(&mut self) -> &mut ::protobuf::RepeatedField<TestRepeatedMessages> {
        &mut self.messages1
    }

    // Take field
    pub fn take_messages1(&mut self) -> ::protobuf::RepeatedField<TestRepeatedMessages> {
        ::std::mem::replace(&mut self.messages1, ::protobuf::RepeatedField::new())
    }

    // repeated .perftest_data.TestRepeatedMessages messages2 = 2;


    pub fn get_messages2(&self) -> &[TestRepeatedMessages] {
        &self.messages2
    }
    pub fn clear_messages2(&mut self) {
        self.messages2.clear();
    }

    // Param is passed by value, moved
    pub fn set_messages2(&mut self, v: ::protobuf::RepeatedField<TestRepeatedMessages>) {
        self.messages2 = v;
    }

    // Mutable pointer to the field.
    pub fn mut_messages2(&mut self) -> &mut ::protobuf::RepeatedField<TestRepeatedMessages> {
        &mut self.messages2
    }

    // Take field
    pub fn take_messages2(&mut self) -> ::protobuf::RepeatedField<TestRepeatedMessages> {
        ::std::mem::replace(&mut self.messages2, ::protobuf::RepeatedField::new())
    }

    // repeated .perftest_data.TestRepeatedMessages messages3 = 3;


    pub fn get_messages3(&self) -> &[TestRepeatedMessages] {
        &self.messages3
    }
    pub fn clear_messages3(&mut self) {
        self.messages3.clear();
    }

    // Param is passed by value, moved
    pub fn set_messages3(&mut self, v: ::protobuf::RepeatedField<TestRepeatedMessages>) {
        self.messages3 = v;
    }

    // Mutable pointer to the field.
    pub fn mut_messages3(&mut self) -> &mut ::protobuf::RepeatedField<TestRepeatedMessages> {
        &mut self.messages3
    }

    // Take field
    pub fn take_messages3(&mut self) -> ::protobuf::RepeatedField<TestRepeatedMessages> {
        ::std::mem::replace(&mut self.messages3, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for TestRepeatedMessages {
    fn is_initialized(&self) -> bool {
        for v in &self.messages1 {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.messages2 {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.messages3 {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.messages1)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.messages2)?;
                },
                3 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.messages3)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.messages1 {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        for value in &self.messages2 {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        for value in &self.messages3 {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.messages1 {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        for v in &self.messages2 {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        for v in &self.messages3 {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TestRepeatedMessages {
        TestRepeatedMessages::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TestRepeatedMessages>>(
                "messages1",
                |m: &TestRepeatedMessages| { &m.messages1 },
                |m: &mut TestRepeatedMessages| { &mut m.messages1 },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TestRepeatedMessages>>(
                "messages2",
                |m: &TestRepeatedMessages| { &m.messages2 },
                |m: &mut TestRepeatedMessages| { &mut m.messages2 },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TestRepeatedMessages>>(
                "messages3",
                |m: &TestRepeatedMessages| { &m.messages3 },
                |m: &mut TestRepeatedMessages| { &mut m.messages3 },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TestRepeatedMessages>(
                "TestRepeatedMessages",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TestRepeatedMessages {
        static instance: ::protobuf::rt::LazyV2<TestRepeatedMessages> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TestRepeatedMessages::new)
    }
}

impl ::protobuf::Clear for TestRepeatedMessages {
    fn clear(&mut self) {
        self.messages1.clear();
        self.messages2.clear();
        self.messages3.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TestRepeatedMessages {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TestRepeatedMessages {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct TestOptionalMessages {
    // message fields
    pub message1: ::protobuf::SingularPtrField<TestOptionalMessages>,
    pub message2: ::protobuf::SingularPtrField<TestOptionalMessages>,
    pub message3: ::protobuf::SingularPtrField<TestOptionalMessages>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TestOptionalMessages {
    fn default() -> &'a TestOptionalMessages {
        <TestOptionalMessages as ::protobuf::Message>::default_instance()
    }
}

impl TestOptionalMessages {
    pub fn new() -> TestOptionalMessages {
        ::std::default::Default::default()
    }

    // optional .perftest_data.TestOptionalMessages message1 = 1;


    pub fn get_message1(&self) -> &TestOptionalMessages {
        self.message1.as_ref().unwrap_or_else(|| <TestOptionalMessages as ::protobuf::Message>::default_instance())
    }
    pub fn clear_message1(&mut self) {
        self.message1.clear();
    }

    pub fn has_message1(&self) -> bool {
        self.message1.is_some()
    }

    // Param is passed by value, moved
    pub fn set_message1(&mut self, v: TestOptionalMessages) {
        self.message1 = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_message1(&mut self) -> &mut TestOptionalMessages {
        if self.message1.is_none() {
            self.message1.set_default();
        }
        self.message1.as_mut().unwrap()
    }

    // Take field
    pub fn take_message1(&mut self) -> TestOptionalMessages {
        self.message1.take().unwrap_or_else(|| TestOptionalMessages::new())
    }

    // optional .perftest_data.TestOptionalMessages message2 = 2;


    pub fn get_message2(&self) -> &TestOptionalMessages {
        self.message2.as_ref().unwrap_or_else(|| <TestOptionalMessages as ::protobuf::Message>::default_instance())
    }
    pub fn clear_message2(&mut self) {
        self.message2.clear();
    }

    pub fn has_message2(&self) -> bool {
        self.message2.is_some()
    }

    // Param is passed by value, moved
    pub fn set_message2(&mut self, v: TestOptionalMessages) {
        self.message2 = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_message2(&mut self) -> &mut TestOptionalMessages {
        if self.message2.is_none() {
            self.message2.set_default();
        }
        self.message2.as_mut().unwrap()
    }

    // Take field
    pub fn take_message2(&mut self) -> TestOptionalMessages {
        self.message2.take().unwrap_or_else(|| TestOptionalMessages::new())
    }

    // optional .perftest_data.TestOptionalMessages message3 = 3;


    pub fn get_message3(&self) -> &TestOptionalMessages {
        self.message3.as_ref().unwrap_or_else(|| <TestOptionalMessages as ::protobuf::Message>::default_instance())
    }
    pub fn clear_message3(&mut self) {
        self.message3.clear();
    }

    pub fn has_message3(&self) -> bool {
        self.message3.is_some()
    }

    // Param is passed by value, moved
    pub fn set_message3(&mut self, v: TestOptionalMessages) {
        self.message3 = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_message3(&mut self) -> &mut TestOptionalMessages {
        if self.message3.is_none() {
            self.message3.set_default();
        }
        self.message3.as_mut().unwrap()
    }

    // Take field
    pub fn take_message3(&mut self) -> TestOptionalMessages {
        self.message3.take().unwrap_or_else(|| TestOptionalMessages::new())
    }
}

impl ::protobuf::Message for TestOptionalMessages {
    fn is_initialized(&self) -> bool {
        for v in &self.message1 {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.message2 {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.message3 {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.message1)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.message2)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.message3)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.message1.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.message2.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.message3.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.message1.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.message2.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.message3.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TestOptionalMessages {
        TestOptionalMessages::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TestOptionalMessages>>(
                "message1",
                |m: &TestOptionalMessages| { &m.message1 },
                |m: &mut TestOptionalMessages| { &mut m.message1 },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TestOptionalMessages>>(
                "message2",
                |m: &TestOptionalMessages| { &m.message2 },
                |m: &mut TestOptionalMessages| { &mut m.message2 },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TestOptionalMessages>>(
                "message3",
                |m: &TestOptionalMessages| { &m.message3 },
                |m: &mut TestOptionalMessages| { &mut m.message3 },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TestOptionalMessages>(
                "TestOptionalMessages",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TestOptionalMessages {
        static instance: ::protobuf::rt::LazyV2<TestOptionalMessages> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TestOptionalMessages::new)
    }
}

impl ::protobuf::Clear for TestOptionalMessages {
    fn clear(&mut self) {
        self.message1.clear();
        self.message2.clear();
        self.message3.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TestOptionalMessages {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TestOptionalMessages {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct TestStrings {
    // message fields
    s1: ::protobuf::SingularField<::std::string::String>,
    s2: ::protobuf::SingularField<::std::string::String>,
    s3: ::protobuf::SingularField<::std::string::String>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TestStrings {
    fn default() -> &'a TestStrings {
        <TestStrings as ::protobuf::Message>::default_instance()
    }
}

impl TestStrings {
    pub fn new() -> TestStrings {
        ::std::default::Default::default()
    }

    // optional string s1 = 1;


    pub fn get_s1(&self) -> &str {
        match self.s1.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_s1(&mut self) {
        self.s1.clear();
    }

    pub fn has_s1(&self) -> bool {
        self.s1.is_some()
    }

    // Param is passed by value, moved
    pub fn set_s1(&mut self, v: ::std::string::String) {
        self.s1 = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_s1(&mut self) -> &mut ::std::string::String {
        if self.s1.is_none() {
            self.s1.set_default();
        }
        self.s1.as_mut().unwrap()
    }

    // Take field
    pub fn take_s1(&mut self) -> ::std::string::String {
        self.s1.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string s2 = 2;


    pub fn get_s2(&self) -> &str {
        match self.s2.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_s2(&mut self) {
        self.s2.clear();
    }

    pub fn has_s2(&self) -> bool {
        self.s2.is_some()
    }

    // Param is passed by value, moved
    pub fn set_s2(&mut self, v: ::std::string::String) {
        self.s2 = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_s2(&mut self) -> &mut ::std::string::String {
        if self.s2.is_none() {
            self.s2.set_default();
        }
        self.s2.as_mut().unwrap()
    }

    // Take field
    pub fn take_s2(&mut self) -> ::std::string::String {
        self.s2.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string s3 = 3;


    pub fn get_s3(&self) -> &str {
        match self.s3.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_s3(&mut self) {
        self.s3.clear();
    }

    pub fn has_s3(&self) -> bool {
        self.s3.is_some()
    }

    // Param is passed by value, moved
    pub fn set_s3(&mut self, v: ::std::string::String) {
        self.s3 = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_s3(&mut self) -> &mut ::std::string::String {
        if self.s3.is_none() {
            self.s3.set_default();
        }
        self.s3.as_mut().unwrap()
    }

    // Take field
    pub fn take_s3(&mut self) -> ::std::string::String {
        self.s3.take().unwrap_or_else(|| ::std::string::String::new())
    }
}

impl ::protobuf::Message for TestStrings {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.s1)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.s2)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.s3)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.s1.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        if let Some(ref v) = self.s2.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        if let Some(ref v) = self.s3.as_ref() {
            my_size += ::protobuf::rt::string_size(3, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.s1.as_ref() {
            os.write_string(1, &v)?;
        }
        if let Some(ref v) = self.s2.as_ref() {
            os.write_string(2, &v)?;
        }
        if let Some(ref v) = self.s3.as_ref() {
            os.write_string(3, &v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TestStrings {
        TestStrings::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "s1",
                |m: &TestStrings| { &m.s1 },
                |m: &mut TestStrings| { &mut m.s1 },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "s2",
                |m: &TestStrings| { &m.s2 },
                |m: &mut TestStrings| { &mut m.s2 },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "s3",
                |m: &TestStrings| { &m.s3 },
                |m: &mut TestStrings| { &mut m.s3 },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TestStrings>(
                "TestStrings",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TestStrings {
        static instance: ::protobuf::rt::LazyV2<TestStrings> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TestStrings::new)
    }
}

impl ::protobuf::Clear for TestStrings {
    fn clear(&mut self) {
        self.s1.clear();
        self.s2.clear();
        self.s3.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TestStrings {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TestStrings {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct TestBytes {
    // message fields
    b1: ::protobuf::SingularField<::std::vec::Vec<u8>>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TestBytes {
    fn default() -> &'a TestBytes {
        <TestBytes as ::protobuf::Message>::default_instance()
    }
}

impl TestBytes {
    pub fn new() -> TestBytes {
        ::std::default::Default::default()
    }

    // optional bytes b1 = 1;


    pub fn get_b1(&self) -> &[u8] {
        match self.b1.as_ref() {
            Some(v) => &v,
            None => &[],
        }
    }
    pub fn clear_b1(&mut self) {
        self.b1.clear();
    }

    pub fn has_b1(&self) -> bool {
        self.b1.is_some()
    }

    // Param is passed by value, moved
    pub fn set_b1(&mut self, v: ::std::vec::Vec<u8>) {
        self.b1 = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_b1(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.b1.is_none() {
            self.b1.set_default();
        }
        self.b1.as_mut().unwrap()
    }

    // Take field
    pub fn take_b1(&mut self) -> ::std::vec::Vec<u8> {
        self.b1.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for TestBytes {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_bytes_into(wire_type, is, &mut self.b1)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.b1.as_ref() {
            my_size += ::protobuf::rt::bytes_size(1, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.b1.as_ref() {
            os.write_bytes(1, &v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TestBytes {
        TestBytes::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "b1",
                |m: &TestBytes| { &m.b1 },
                |m: &mut TestBytes| { &mut m.b1 },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TestBytes>(
                "TestBytes",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TestBytes {
        static instance: ::protobuf::rt::LazyV2<TestBytes> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TestBytes::new)
    }
}

impl ::protobuf::Clear for TestBytes {
    fn clear(&mut self) {
        self.b1.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TestBytes {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TestBytes {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct PerftestData {
    // message fields
    pub test1: ::protobuf::RepeatedField<Test1>,
    pub test_repeated_bool: ::protobuf::RepeatedField<TestRepeatedBool>,
    pub test_repeated_messages: ::protobuf::RepeatedField<TestRepeatedMessages>,
    pub test_optional_messages: ::protobuf::RepeatedField<TestOptionalMessages>,
    pub test_strings: ::protobuf::RepeatedField<TestStrings>,
    pub test_repeated_packed_int32: ::protobuf::RepeatedField<TestRepeatedPackedInt32>,
    pub test_small_bytearrays: ::protobuf::RepeatedField<TestBytes>,
    pub test_large_bytearrays: ::protobuf::RepeatedField<TestBytes>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a PerftestData {
    fn default() -> &'a PerftestData {
        <PerftestData as ::protobuf::Message>::default_instance()
    }
}

impl PerftestData {
    pub fn new() -> PerftestData {
        ::std::default::Default::default()
    }

    // repeated .perftest_data.Test1 test1 = 1;


    pub fn get_test1(&self) -> &[Test1] {
        &self.test1
    }
    pub fn clear_test1(&mut self) {
        self.test1.clear();
    }

    // Param is passed by value, moved
    pub fn set_test1(&mut self, v: ::protobuf::RepeatedField<Test1>) {
        self.test1 = v;
    }

    // Mutable pointer to the field.
    pub fn mut_test1(&mut self) -> &mut ::protobuf::RepeatedField<Test1> {
        &mut self.test1
    }

    // Take field
    pub fn take_test1(&mut self) -> ::protobuf::RepeatedField<Test1> {
        ::std::mem::replace(&mut self.test1, ::protobuf::RepeatedField::new())
    }

    // repeated .perftest_data.TestRepeatedBool test_repeated_bool = 2;


    pub fn get_test_repeated_bool(&self) -> &[TestRepeatedBool] {
        &self.test_repeated_bool
    }
    pub fn clear_test_repeated_bool(&mut self) {
        self.test_repeated_bool.clear();
    }

    // Param is passed by value, moved
    pub fn set_test_repeated_bool(&mut self, v: ::protobuf::RepeatedField<TestRepeatedBool>) {
        self.test_repeated_bool = v;
    }

    // Mutable pointer to the field.
    pub fn mut_test_repeated_bool(&mut self) -> &mut ::protobuf::RepeatedField<TestRepeatedBool> {
        &mut self.test_repeated_bool
    }

    // Take field
    pub fn take_test_repeated_bool(&mut self) -> ::protobuf::RepeatedField<TestRepeatedBool> {
        ::std::mem::replace(&mut self.test_repeated_bool, ::protobuf::RepeatedField::new())
    }

    // repeated .perftest_data.TestRepeatedMessages test_repeated_messages = 3;


    pub fn get_test_repeated_messages(&self) -> &[TestRepeatedMessages] {
        &self.test_repeated_messages
    }
    pub fn clear_test_repeated_messages(&mut self) {
        self.test_repeated_messages.clear();
    }

    // Param is passed by value, moved
    pub fn set_test_repeated_messages(&mut self, v: ::protobuf::RepeatedField<TestRepeatedMessages>) {
        self.test_repeated_messages = v;
    }

    // Mutable pointer to the field.
    pub fn mut_test_repeated_messages(&mut self) -> &mut ::protobuf::RepeatedField<TestRepeatedMessages> {
        &mut self.test_repeated_messages
    }

    // Take field
    pub fn take_test_repeated_messages(&mut self) -> ::protobuf::RepeatedField<TestRepeatedMessages> {
        ::std::mem::replace(&mut self.test_repeated_messages, ::protobuf::RepeatedField::new())
    }

    // repeated .perftest_data.TestOptionalMessages test_optional_messages = 4;


    pub fn get_test_optional_messages(&self) -> &[TestOptionalMessages] {
        &self.test_optional_messages
    }
    pub fn clear_test_optional_messages(&mut self) {
        self.test_optional_messages.clear();
    }

    // Param is passed by value, moved
    pub fn set_test_optional_messages(&mut self, v: ::protobuf::RepeatedField<TestOptionalMessages>) {
        self.test_optional_messages = v;
    }

    // Mutable pointer to the field.
    pub fn mut_test_optional_messages(&mut self) -> &mut ::protobuf::RepeatedField<TestOptionalMessages> {
        &mut self.test_optional_messages
    }

    // Take field
    pub fn take_test_optional_messages(&mut self) -> ::protobuf::RepeatedField<TestOptionalMessages> {
        ::std::mem::replace(&mut self.test_optional_messages, ::protobuf::RepeatedField::new())
    }

    // repeated .perftest_data.TestStrings test_strings = 5;


    pub fn get_test_strings(&self) -> &[TestStrings] {
        &self.test_strings
    }
    pub fn clear_test_strings(&mut self) {
        self.test_strings.clear();
    }

    // Param is passed by value, moved
    pub fn set_test_strings(&mut self, v: ::protobuf::RepeatedField<TestStrings>) {
        self.test_strings = v;
    }

    // Mutable pointer to the field.
    pub fn mut_test_strings(&mut self) -> &mut ::protobuf::RepeatedField<TestStrings> {
        &mut self.test_strings
    }

    // Take field
    pub fn take_test_strings(&mut self) -> ::protobuf::RepeatedField<TestStrings> {
        ::std::mem::replace(&mut self.test_strings, ::protobuf::RepeatedField::new())
    }

    // repeated .perftest_data.TestRepeatedPackedInt32 test_repeated_packed_int32 = 6;


    pub fn get_test_repeated_packed_int32(&self) -> &[TestRepeatedPackedInt32] {
        &self.test_repeated_packed_int32
    }
    pub fn clear_test_repeated_packed_int32(&mut self) {
        self.test_repeated_packed_int32.clear();
    }

    // Param is passed by value, moved
    pub fn set_test_repeated_packed_int32(&mut self, v: ::protobuf::RepeatedField<TestRepeatedPackedInt32>) {
        self.test_repeated_packed_int32 = v;
    }

    // Mutable pointer to the field.
    pub fn mut_test_repeated_packed_int32(&mut self) -> &mut ::protobuf::RepeatedField<TestRepeatedPackedInt32> {
        &mut self.test_repeated_packed_int32
    }

    // Take field
    pub fn take_test_repeated_packed_int32(&mut self) -> ::protobuf::RepeatedField<TestRepeatedPackedInt32> {
        ::std::mem::replace(&mut self.test_repeated_packed_int32, ::protobuf::RepeatedField::new())
    }

    // repeated .perftest_data.TestBytes test_small_bytearrays = 7;


    pub fn get_test_small_bytearrays(&self) -> &[TestBytes] {
        &self.test_small_bytearrays
    }
    pub fn clear_test_small_bytearrays(&mut self) {
        self.test_small_bytearrays.clear();
    }

    // Param is passed by value, moved
    pub fn set_test_small_bytearrays(&mut self, v: ::protobuf::RepeatedField<TestBytes>) {
        self.test_small_bytearrays = v;
    }

    // Mutable pointer to the field.
    pub fn mut_test_small_bytearrays(&mut self) -> &mut ::protobuf::RepeatedField<TestBytes> {
        &mut self.test_small_bytearrays
    }

    // Take field
    pub fn take_test_small_bytearrays(&mut self) -> ::protobuf::RepeatedField<TestBytes> {
        ::std::mem::replace(&mut self.test_small_bytearrays, ::protobuf::RepeatedField::new())
    }

    // repeated .perftest_data.TestBytes test_large_bytearrays = 8;


    pub fn get_test_large_bytearrays(&self) -> &[TestBytes] {
        &self.test_large_bytearrays
    }
    pub fn clear_test_large_bytearrays(&mut self) {
        self.test_large_bytearrays.clear();
    }

    // Param is passed by value, moved
    pub fn set_test_large_bytearrays(&mut self, v: ::protobuf::RepeatedField<TestBytes>) {
        self.test_large_bytearrays = v;
    }

    // Mutable pointer to the field.
    pub fn mut_test_large_bytearrays(&mut self) -> &mut ::protobuf::RepeatedField<TestBytes> {
        &mut self.test_large_bytearrays
    }

    // Take field
    pub fn take_test_large_bytearrays(&mut self) -> ::protobuf::RepeatedField<TestBytes> {
        ::std::mem::replace(&mut self.test_large_bytearrays, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for PerftestData {
    fn is_initialized(&self) -> bool {
        for v in &self.test1 {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.test_repeated_bool {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.test_repeated_messages {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.test_optional_messages {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.test_strings {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.test_repeated_packed_int32 {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.test_small_bytearrays {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.test_large_bytearrays {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.test1)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.test_repeated_bool)?;
                },
                3 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.test_repeated_messages)?;
                },
                4 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.test_optional_messages)?;
                },
                5 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.test_strings)?;
                },
                6 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.test_repeated_packed_int32)?;
                },
                7 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.test_small_bytearrays)?;
                },
                8 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.test_large_bytearrays)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.test1 {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        for value in &self.test_repeated_bool {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        for value in &self.test_repeated_messages {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        for value in &self.test_optional_messages {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        for value in &self.test_strings {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        for value in &self.test_repeated_packed_int32 {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        for value in &self.test_small_bytearrays {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        for value in &self.test_large_bytearrays {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.test1 {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        for v in &self.test_repeated_bool {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        for v in &self.test_repeated_messages {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        for v in &self.test_optional_messages {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        for v in &self.test_strings {
            os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        for v in &self.test_repeated_packed_int32 {
            os.write_tag(6, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        for v in &self.test_small_bytearrays {
            os.write_tag(7, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        for v in &self.test_large_bytearrays {
            os.write_tag(8, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> PerftestData {
        PerftestData::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Test1>>(
                "test1",
                |m: &PerftestData| { &m.test1 },
                |m: &mut PerftestData| { &mut m.test1 },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TestRepeatedBool>>(
                "test_repeated_bool",
                |m: &PerftestData| { &m.test_repeated_bool },
                |m: &mut PerftestData| { &mut m.test_repeated_bool },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TestRepeatedMessages>>(
                "test_repeated_messages",
                |m: &PerftestData| { &m.test_repeated_messages },
                |m: &mut PerftestData| { &mut m.test_repeated_messages },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TestOptionalMessages>>(
                "test_optional_messages",
                |m: &PerftestData| { &m.test_optional_messages },
                |m: &mut PerftestData| { &mut m.test_optional_messages },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TestStrings>>(
                "test_strings",
                |m: &PerftestData| { &m.test_strings },
                |m: &mut PerftestData| { &mut m.test_strings },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TestRepeatedPackedInt32>>(
                "test_repeated_packed_int32",
                |m: &PerftestData| { &m.test_repeated_packed_int32 },
                |m: &mut PerftestData| { &mut m.test_repeated_packed_int32 },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TestBytes>>(
                "test_small_bytearrays",
                |m: &PerftestData| { &m.test_small_bytearrays },
                |m: &mut PerftestData| { &mut m.test_small_bytearrays },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TestBytes>>(
                "test_large_bytearrays",
                |m: &PerftestData| { &m.test_large_bytearrays },
                |m: &mut PerftestData| { &mut m.test_large_bytearrays },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<PerftestData>(
                "PerftestData",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static PerftestData {
        static instance: ::protobuf::rt::LazyV2<PerftestData> = ::protobuf::rt::LazyV2::INIT;
        instance.get(PerftestData::new)
    }
}

impl ::protobuf::Clear for PerftestData {
    fn clear(&mut self) {
        self.test1.clear();
        self.test_repeated_bool.clear();
        self.test_repeated_messages.clear();
        self.test_optional_messages.clear();
        self.test_strings.clear();
        self.test_repeated_packed_int32.clear();
        self.test_small_bytearrays.clear();
        self.test_large_bytearrays.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for PerftestData {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PerftestData {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x13perftest_data.proto\x12\rperftest_data\"!\n\x05Test1\x12\x16\n\x05\
    value\x18\x01\x20\x01(\x05R\x05valueB\0:\0\".\n\x10TestRepeatedBool\x12\
    \x18\n\x06values\x18\x01\x20\x03(\x08R\x06valuesB\0:\0\"7\n\x17TestRepea\
    tedPackedInt32\x12\x1a\n\x06values\x18\x01\x20\x03(\x05R\x06valuesB\x02\
    \x10\x01:\0\"\xe7\x01\n\x14TestRepeatedMessages\x12C\n\tmessages1\x18\
    \x01\x20\x03(\x0b2#.perftest_data.TestRepeatedMessagesR\tmessages1B\0\
    \x12C\n\tmessages2\x18\x02\x20\x03(\x0b2#.perftest_data.TestRepeatedMess\
    agesR\tmessages2B\0\x12C\n\tmessages3\x18\x03\x20\x03(\x0b2#.perftest_da\
    ta.TestRepeatedMessagesR\tmessages3B\0:\0\"\xe1\x01\n\x14TestOptionalMes\
    sages\x12A\n\x08message1\x18\x01\x20\x01(\x0b2#.perftest_data.TestOption\
    alMessagesR\x08message1B\0\x12A\n\x08message2\x18\x02\x20\x01(\x0b2#.per\
    ftest_data.TestOptionalMessagesR\x08message2B\0\x12A\n\x08message3\x18\
    \x03\x20\x01(\x0b2#.perftest_data.TestOptionalMessagesR\x08message3B\0:\
    \0\"E\n\x0bTestStrings\x12\x10\n\x02s1\x18\x01\x20\x01(\tR\x02s1B\0\x12\
    \x10\n\x02s2\x18\x02\x20\x01(\tR\x02s2B\0\x12\x10\n\x02s3\x18\x03\x20\
    \x01(\tR\x02s3B\0:\0\"\x1f\n\tTestBytes\x12\x10\n\x02b1\x18\x01\x20\x01(\
    \x0cR\x02b1B\0:\0\"\x91\x05\n\x0cPerftestData\x12,\n\x05test1\x18\x01\
    \x20\x03(\x0b2\x14.perftest_data.Test1R\x05test1B\0\x12O\n\x12test_repea\
    ted_bool\x18\x02\x20\x03(\x0b2\x1f.perftest_data.TestRepeatedBoolR\x10te\
    stRepeatedBoolB\0\x12[\n\x16test_repeated_messages\x18\x03\x20\x03(\x0b2\
    #.perftest_data.TestRepeatedMessagesR\x14testRepeatedMessagesB\0\x12[\n\
    \x16test_optional_messages\x18\x04\x20\x03(\x0b2#.perftest_data.TestOpti\
    onalMessagesR\x14testOptionalMessagesB\0\x12?\n\x0ctest_strings\x18\x05\
    \x20\x03(\x0b2\x1a.perftest_data.TestStringsR\x0btestStringsB\0\x12e\n\
    \x1atest_repeated_packed_int32\x18\x06\x20\x03(\x0b2&.perftest_data.Test\
    RepeatedPackedInt32R\x17testRepeatedPackedInt32B\0\x12N\n\x15test_small_\
    bytearrays\x18\x07\x20\x03(\x0b2\x18.perftest_data.TestBytesR\x13testSma\
    llBytearraysB\0\x12N\n\x15test_large_bytearrays\x18\x08\x20\x03(\x0b2\
    \x18.perftest_data.TestBytesR\x13testLargeBytearraysB\0:\0B\0b\x06proto2\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
